name: Latihan-CI 

on: 
    push: 
        branches: [main]
    pull_request:

jobs: 
    test-and-build: 
        runs-on: ubuntu-latest

        steps: 
            - name: Ambil Kode
              uses: actions/checkout@v4 

            - name: Setup Node.js 
              uses: actions/setup-node@v4
              with: 
                node-version: '20'
                cache: npm 
            
            - name: Install Dependencies
              run: npm ci

            - name: Jalankan Tests
              run: npm test

            - name: Build Aplikasi
              run: npm run build
