name: Deploy Production 

on: 
    push: 
        branches: [main]

permissions:
    contents: read 
    pages: write
    id-token: write

concurrency: 
    group: pages
    cancel-in-progress: false

jobs: 
    build: 
        runs-on: ubuntu-latest

        steps: 
            - name: Ambil Kode
              uses: actions/checkout@v4 

            - name: Setup Node.js 
              uses: actions/setup-node@v4
              with: 
                node-version: '20'
                cache: npm 
            
            - name: Install Dependencies
              run: npm ci

            - name: Jalankan Tests
              run: npm test

            - name: Build Aplikasi
              run: npm run build

            - name: Setup Github Pages 
              uses: actions/configure-pages@v5

            - name: Upload hasil build 
              uses: actions/upload-pages-artifact@v3
              with: 
                path: ./dist
                
    deploy: 
        environment: 
            name: production
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Deploy ke GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
